# Generated by Django 5.1.6 on 2025-02-24 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='customer',
        ),
        migrations.AddField(
            model_name='donation',
            name='cause',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='app.cause'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
